//created on: 06-ene-2014
package es.uclm.sri.reglas.drools

//list any import classes here.
import es.uclm.sri.entidades.Album;
import es.uclm.sri.entidades.Recomendacion;


//declare any global variables here




rule ""

    when
        Recomendacion(  )
    then
        //actions

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end