package es.uclm.sri.reglas.drools

//list any import classes here.
import es.uclm.sri.entidades.Album;
import es.uclm.sri.entidades.Recomendacion;

//declare any global variables here



rule "Es recomendaci—n reiterativa"

    when
    	
        recomendacion : Recomendacion( fecha <  );
        
    then
        //actions

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end